# Properties format
#spring.application.name=ecom-microservice
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#info.app.name=Ecom Microservice Application

# YAML format
spring:
  application:
    name: ecom-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: ecomuser
    password: ecompass
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
          ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  Uncomment below lines to use H2 in-memory database
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:commdb
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


management:
  endpoints:
    web:
      exposure:
        include: beans,health,info,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: Ecom Microservice Application
    description: This e-commerce backend system using microservice architecture.
    version: 1.0.0
  env:
    enabled: true



